# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/default-image.jpg', upload_to='images')),
                ('tutoring_experience', models.TextField()),
                ('tutoring_approach', models.TextField()),
                ('language', models.CharField(default='', max_length=50)),
                ('availability', models.CharField(default='', max_length=50)),
                ('reference', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
