# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subjects_tutor'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_tutor', to='subjects.Subjects'),
        ),
    ]
